#!/usr/bin/env /bin/bash
export PATH=/home/main/Downloads/jdk-21/bin/:$PATH
rm -r index 2>/dev/null
java -cp "spring-ai-client-chat-1.0.0-M8.jar:spring-ai-ollama-1.0.0-M8.jar:spring-ai-core-1.0.0-M6.jar:spring-ai-ollama-spring-boot-starter-1.0.0-M6.jar:jackson-annotations-2.19.0.jar:spring-core-7.0.0-M2.jar:../lucene-10.2.0/modules/*:../lucene-10.2.0/modules-thirdparty/*" EvaluateMetrics.java
